version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-up
    ports:
      - "8055:8080"
    volumes:
      - .:/app
    # stdin_open: true
    # tty: true
    # entrypoint: bash
    entrypoint: bash -c "swift build && swift run"
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=i3
      - MYSQL_USER=i3
      - MYSQL_PASSWORD=i3
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
